version: '3.3'

services:
    encoder:
      image: encoder
      hostname: encoder
      ports:
          - "8080:8080"
      environment:
          ENCODER_HOST: 0.0.0.0
          ENCODER_PORT: 8080
          MINIO_HOST: minio
          MINIO_PORT: 9000
          MINIO_ACCESS_KEY: ISUHFISUDHFISDFH
          MINIO_SECRET_KEY: aisuhfishfiasuhfwhf2389fhsofaoj
          MINIO_INIT_DELAY: 3
          MINIO_INIT_TRIES: 3
          MINIO_HEALTHCHECK_PATH: /minio/health/live
    minio:
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        hostname: minio
        volumes:
            - /tmp/minio:/export
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: ISUHFISUDHFISDFH
            MINIO_SECRET_KEY: aisuhfishfiasuhfwhf2389fhsofaoj
        deploy:
            restart_policy:
                delay: 10s
                max_attempts: 10
                window: 60s
        command: server /export
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
